# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Graphicus03_Main_2.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Graphicus03(object):
    def setupUi(self, Graphicus03):
        if not Graphicus03.objectName():
            Graphicus03.setObjectName(u"Graphicus03")
        Graphicus03.resize(300, 500)
        Graphicus03.setMinimumSize(QSize(300, 500))
        Graphicus03.setMaximumSize(QSize(300, 500))
        self.centralwidget = QWidget(Graphicus03)
        self.centralwidget.setObjectName(u"centralwidget")
        self.LE_csvFile = QLineEdit(self.centralwidget)
        self.LE_csvFile.setObjectName(u"LE_csvFile")
        self.LE_csvFile.setGeometry(QRect(12, 60, 201, 20))
        self.LB_title = QLabel(self.centralwidget)
        self.LB_title.setObjectName(u"LB_title")
        self.LB_title.setGeometry(QRect(0, 0, 301, 51))
        font = QFont()
        font.setFamily(u"Source Code Pro")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.LB_title.setFont(font)
        self.LB_title.setAlignment(Qt.AlignCenter)
        self.PB_selectFile = QPushButton(self.centralwidget)
        self.PB_selectFile.setObjectName(u"PB_selectFile")
        self.PB_selectFile.setGeometry(QRect(220, 60, 71, 23))
        font1 = QFont()
        font1.setFamily(u"Source Sans Pro")
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setWeight(50)
        self.PB_selectFile.setFont(font1)
        self.LB_radius = QLabel(self.centralwidget)
        self.LB_radius.setObjectName(u"LB_radius")
        self.LB_radius.setGeometry(QRect(10, 90, 91, 21))
        font2 = QFont()
        font2.setFamily(u"Source Serif Pro")
        font2.setPointSize(16)
        font2.setBold(True)
        font2.setWeight(75)
        self.LB_radius.setFont(font2)
        self.DSB_radius = QDoubleSpinBox(self.centralwidget)
        self.DSB_radius.setObjectName(u"DSB_radius")
        self.DSB_radius.setGeometry(QRect(120, 90, 91, 21))
        font3 = QFont()
        font3.setFamily(u"Source Sans Pro")
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setWeight(50)
        self.DSB_radius.setFont(font3)
        self.DSB_radius.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.DSB_radius.setAccelerated(True)
        self.DSB_radius.setSingleStep(0.100000000000000)
        self.LB_material = QLabel(self.centralwidget)
        self.LB_material.setObjectName(u"LB_material")
        self.LB_material.setGeometry(QRect(10, 120, 101, 21))
        self.LB_material.setFont(font2)
        self.CB_material = QComboBox(self.centralwidget)
        self.CB_material.setObjectName(u"CB_material")
        self.CB_material.setGeometry(QRect(120, 120, 171, 22))
        self.CB_material.setFont(font1)
        self.CB_unit_radius = QComboBox(self.centralwidget)
        self.CB_unit_radius.setObjectName(u"CB_unit_radius")
        self.CB_unit_radius.setGeometry(QRect(220, 90, 71, 22))
        self.CB_unit_radius.setFont(font1)
        self.PB_launch = QPushButton(self.centralwidget)
        self.PB_launch.setObjectName(u"PB_launch")
        self.PB_launch.setGeometry(QRect(10, 380, 281, 41))
        font4 = QFont()
        font4.setFamily(u"Source Sans Pro")
        font4.setPointSize(16)
        font4.setBold(True)
        font4.setWeight(75)
        self.PB_launch.setFont(font4)
        self.GV_logo = QGraphicsView(self.centralwidget)
        self.GV_logo.setObjectName(u"GV_logo")
        self.GV_logo.setGeometry(QRect(10, 150, 281, 151))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(10, 430, 281, 23))
        self.progressBar.setValue(24)
        self.GB_dimensions = QGroupBox(self.centralwidget)
        self.GB_dimensions.setObjectName(u"GB_dimensions")
        self.GB_dimensions.setGeometry(QRect(10, 299, 281, 81))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setWeight(50)
        self.GB_dimensions.setFont(font5)
        self.GB_dimensions.setFlat(False)
        self.GB_dimensions.setCheckable(False)
        self.CB_unit_Hauteur = QComboBox(self.GB_dimensions)
        self.CB_unit_Hauteur.setObjectName(u"CB_unit_Hauteur")
        self.CB_unit_Hauteur.setGeometry(QRect(200, 50, 71, 22))
        font6 = QFont()
        font6.setFamily(u"Source Sans Pro")
        font6.setPointSize(10)
        font6.setBold(False)
        font6.setItalic(False)
        font6.setUnderline(False)
        font6.setWeight(50)
        self.CB_unit_Hauteur.setFont(font6)
        self.DSB_Hauteur = QDoubleSpinBox(self.GB_dimensions)
        self.DSB_Hauteur.setObjectName(u"DSB_Hauteur")
        self.DSB_Hauteur.setGeometry(QRect(100, 50, 91, 21))
        font7 = QFont()
        font7.setFamily(u"Source Sans Pro")
        font7.setPointSize(11)
        font7.setBold(False)
        font7.setItalic(False)
        font7.setUnderline(False)
        font7.setWeight(50)
        self.DSB_Hauteur.setFont(font7)
        self.DSB_Hauteur.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.DSB_Hauteur.setAccelerated(True)
        self.DSB_Hauteur.setSingleStep(0.100000000000000)
        self.CB_unit_Largeur = QComboBox(self.GB_dimensions)
        self.CB_unit_Largeur.setObjectName(u"CB_unit_Largeur")
        self.CB_unit_Largeur.setGeometry(QRect(200, 20, 71, 22))
        self.CB_unit_Largeur.setFont(font6)
        self.DSB_Largeur = QDoubleSpinBox(self.GB_dimensions)
        self.DSB_Largeur.setObjectName(u"DSB_Largeur")
        self.DSB_Largeur.setGeometry(QRect(100, 20, 91, 21))
        self.DSB_Largeur.setFont(font7)
        self.DSB_Largeur.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.DSB_Largeur.setAccelerated(True)
        self.DSB_Largeur.setSingleStep(0.100000000000000)
        self.LB_largeur = QLabel(self.GB_dimensions)
        self.LB_largeur.setObjectName(u"LB_largeur")
        self.LB_largeur.setGeometry(QRect(10, 20, 81, 21))
        font8 = QFont()
        font8.setFamily(u"Source Serif Pro")
        font8.setPointSize(13)
        font8.setBold(True)
        font8.setItalic(False)
        font8.setUnderline(False)
        font8.setWeight(75)
        self.LB_largeur.setFont(font8)
        self.LB_largeur.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.LB_hauteur = QLabel(self.GB_dimensions)
        self.LB_hauteur.setObjectName(u"LB_hauteur")
        self.LB_hauteur.setGeometry(QRect(10, 50, 81, 21))
        self.LB_hauteur.setFont(font8)
        self.LB_hauteur.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        Graphicus03.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Graphicus03)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 300, 21))
        Graphicus03.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(Graphicus03)
        self.statusbar.setObjectName(u"statusbar")
        Graphicus03.setStatusBar(self.statusbar)

        self.retranslateUi(Graphicus03)

        QMetaObject.connectSlotsByName(Graphicus03)
    # setupUi

    def retranslateUi(self, Graphicus03):
        Graphicus03.setWindowTitle(QCoreApplication.translate("Graphicus03", u"MainWindow", None))
        self.LB_title.setText(QCoreApplication.translate("Graphicus03", u"Graphicus03", None))
        self.PB_selectFile.setText(QCoreApplication.translate("Graphicus03", u"Select File", None))
        self.LB_radius.setText(QCoreApplication.translate("Graphicus03", u"Radius :", None))
        self.LB_material.setText(QCoreApplication.translate("Graphicus03", u"Material :", None))
        self.PB_launch.setText(QCoreApplication.translate("Graphicus03", u"LAUNCH", None))
        self.GB_dimensions.setTitle(QCoreApplication.translate("Graphicus03", u"Dimesions de la gravure", None))
        self.LB_largeur.setText(QCoreApplication.translate("Graphicus03", u"Largeur :", None))
        self.LB_hauteur.setText(QCoreApplication.translate("Graphicus03", u"Hauteur :", None))
    # retranslateUi

